const recipes = [
  {
    dishName: "Adobo",
    ingredients: [
      "1 kg chicken or pork",
      "1/2 cup soy sauce",
      "1/2 cup vinegar",
      "1 head garlic, minced",
      "1 onion, chopped",
      "2 bay leaves",
      "1 tsp black peppercorns",
      "1 cup water",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Combine chicken or pork, soy sauce, and garlic in a large bowl. Marinate for at least 30 minutes.",
      "Heat oil in a pot over medium heat. Add the marinated meat and cook until browned.",
      "Add the onions and cook until softened.",
      "Pour in the vinegar, water, bay leaves, and peppercorns. Bring to a boil.",
      "Lower the heat and simmer for 30-40 minutes or until the meat is tender.",
      "Season with salt and pepper to taste.",
      "Serve hot with rice.",
    ],
    preparationTime: "15 minutes",
    cookingTime: "40 minutes",
    servingSize: "4 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2009/08/Pork-Adobo-.jpg",
    category: "main_course",
  },
  {
    dishName: "Sinigang",
    ingredients: [
      "1 kg pork belly",
      "1 packet sinigang mix",
      "1 onion, chopped",
      "2 tomatoes, quartered",
      "1 radish, sliced",
      "1 eggplant, sliced",
      "1 bunch kangkong (water spinach)",
      "6 cups water",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a pot, bring water to a boil. Add the pork and cook until tender.",
      "Add the onions and tomatoes. Cook until softened.",
      "Add the sinigang mix and stir until dissolved.",
      "Add the radish and eggplant. Cook until tender.",
      "Add the kangkong and cook for another 2 minutes.",
      "Season with salt and pepper to taste.",
      "Serve hot with rice.",
    ],
    preparationTime: "20 minutes",
    cookingTime: "50 minutes",
    servingSize: "6 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2022/09/sinigang-na-baboy-730x1095.jpg",
    category: "main_course",
  },
  {
    dishName: "Kare-Kare",
    ingredients: [
      "1 kg oxtail or beef tripe",
      "1/2 cup peanut butter",
      "1/4 cup ground toasted rice",
      "1 bunch bok choy",
      "1 eggplant, sliced",
      "1 banana heart, sliced",
      "1/2 cup bagoong (fermented shrimp paste)",
      "1 onion, chopped",
      "4 cloves garlic, minced",
      "6 cups water",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a pot, boil the oxtail or beef tripe until tender.",
      "Add the peanut butter and ground toasted rice. Stir until well combined.",
      "Add the vegetables and cook until tender.",
      "Season with salt and pepper to taste.",
      "Serve hot with bagoong and rice.",
    ],
    preparationTime: "30 minutes",
    cookingTime: "2 hours",
    servingSize: "6 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2009/05/how-to-cook-kare-kare.jpg",
    category: "main_course",
  },
  {
    dishName: "Lechon Kawali",
    ingredients: [
      "1 kg pork belly",
      "1 tbsp salt",
      "1 tsp peppercorns",
      "4 cloves garlic, crushed",
      "2 bay leaves",
      "Water for boiling",
      "Oil for frying",
    ],
    instructions: [
      "In a pot, combine pork belly, salt, peppercorns, garlic, bay leaves, and water. Boil until tender.",
      "Remove the pork belly and let it cool. Pat dry with paper towels.",
      "Heat oil in a deep fryer or large pot. Fry the pork belly until crispy.",
      "Drain on paper towels and slice into serving pieces.",
      "Serve hot with dipping sauce and rice.",
    ],
    preparationTime: "15 minutes",
    cookingTime: "1 hour",
    servingSize: "4 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2017/12/Lechon-Kawali.jpg",
    category: "main_course",
  },
  {
    dishName: "Chicken Inasal",
    ingredients: [
      "1 kg chicken thighs or drumsticks",
      "1/2 cup calamansi juice",
      "1/4 cup soy sauce",
      "1/4 cup vinegar",
      "1 head garlic, minced",
      "1 thumb-sized ginger, grated",
      "2 tbsp brown sugar",
      "1 tsp ground black pepper",
      "1/4 cup annatto oil",
    ],
    instructions: [
      "In a bowl, combine calamansi juice, soy sauce, vinegar, garlic, ginger, brown sugar, and black pepper. Mix well.",
      "Marinate the chicken in the mixture for at least 1 hour.",
      "Grill the chicken over medium heat, basting with annatto oil, until cooked through.",
      "Serve hot with rice and dipping sauce.",
    ],
    preparationTime: "20 minutes",
    cookingTime: "30 minutes",
    servingSize: "4 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2013/02/Inasal.jpg",
    category: "main_course",
  },
  {
    dishName: "Leche Flan",
    ingredients: [
      "10 egg yolks",
      "1 can (300ml) condensed milk",
      "1 can (370ml) evaporated milk",
      "1 teaspoon vanilla extract",
      "1 cup white sugar (for caramel)",
    ],
    instructions: [
      "Prepare the caramel: Heat the sugar in a saucepan over medium heat, stirring constantly until it melts and turns golden brown. Quickly pour the caramel into a llanera (flan mold) and tilt to coat the bottom evenly. Set aside to cool.",
      "In a mixing bowl, whisk the egg yolks gently, then add the condensed milk, evaporated milk, and vanilla extract. Mix until smooth, avoiding bubbles.",
      "Pour the mixture through a strainer into the llanera with the caramel. Cover the llanera with foil to prevent water from dripping during steaming.",
      "Steam the flan over low heat for 30-35 minutes or until a toothpick inserted in the center comes out clean.",
      "Allow the flan to cool, then refrigerate for at least 2 hours before serving.",
      "To serve, run a knife around the edges of the flan, then invert onto a serving plate.",
    ],
    preparationTime: "15 minutes",
    cookingTime: "35 minutes",
    servingSize: "6 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2009/07/Leche-Flan_-jpg.webp",
    category: "dessert",
  },
  {
    dishName: "Puto Cheese",
    ingredients: [
      "2 cups all-purpose flour",
      "1 tablespoon baking powder",
      "1/2 cup sugar",
      "1 cup evaporated milk",
      "1/2 cup water",
      "1 large egg",
      "1 teaspoon vanilla extract",
      "Cheddar cheese slices (for topping)",
    ],
    instructions: [
      "In a mixing bowl, combine flour, baking powder, and sugar. Mix well.",
      "In another bowl, whisk together evaporated milk, water, egg, and vanilla extract.",
      "Gradually pour the wet ingredients into the dry ingredients, mixing until smooth and free of lumps.",
      "Pour the batter into small puto molds, filling them about 3/4 full.",
      "Top each with a slice of cheddar cheese.",
      "Steam over medium heat for 10-12 minutes or until a toothpick inserted into the puto comes out clean.",
      "Allow to cool slightly before serving.",
    ],
    preparationTime: "10 minutes",
    cookingTime: "12 minutes",
    servingSize: "8 servings",
    imageUrl:
      "https://panlasangpinoy.com/wp-content/uploads/2016/12/Puto-Cheese_.jpg",
    category: "dessert",
  },
  {
    dishName: "Turon",
    ingredients: [
      "6 ripe saba bananas, peeled and halved lengthwise",
      "1 cup ripe jackfruit (langka), strips",
      "1/2 cup brown sugar",
      "12 spring roll wrappers",
      "Oil for frying",
    ],
    instructions: [
      "Roll the banana halves in brown sugar until coated.",
      "Place a banana half and a few strips of jackfruit on a spring roll wrapper. Fold and roll the wrapper tightly, sealing the edges with water.",
      "Repeat with the remaining bananas and wrappers.",
      "Heat oil in a frying pan over medium heat. Fry the turon in batches until golden brown and crispy, about 2-3 minutes per side.",
      "Drain on paper towels and serve warm.",
    ],
    preparationTime: "10 minutes",
    cookingTime: "10 minutes",
    servingSize: "6 servings",
    imageUrl: "https://panlasangpinoy.com/wp-content/uploads/2009/06/Turon.jpg",
    category: "dessert",
  },
  {
    dishName: "Tapsilog",
    ingredients: [
      "500g beef sirloin, thinly sliced",
      "1/4 cup soy sauce",
      "3 tablespoons calamansi juice (or lemon juice)",
      "4 cloves garlic, minced",
      "2 tablespoons sugar",
      "1/2 teaspoon black pepper",
      "3 cups cooked garlic fried rice (sinangag)",
      "4 fried eggs (sunny-side-up)"
    ],
    instructions: [
      "In a bowl, combine soy sauce, calamansi juice, garlic, sugar, and black pepper. Mix well.",
      "Marinate the beef slices in the mixture for at least 1 hour or overnight for best results.",
      "Heat a pan over medium heat and cook the marinated beef in batches until browned and tender. Set aside.",
      "Prepare garlic fried rice by sautéing minced garlic in a pan with oil until golden. Add cold, cooked rice and stir-fry until evenly coated with garlic. Season with salt.",
      "Fry the eggs sunny-side-up.",
      "Assemble the dish by plating the beef tapa, garlic fried rice, and fried egg together. Serve hot."
    ],
    preparationTime: "10 minutes",
    cookingTime: "20 minutes",
    servingSize: "4 servings",
    imageUrl: "https://panlasangpinoy.com/wp-content/uploads/2015/03/tapsilog-recipe.jpg",
    category: "breakfast"
}
];

module.exports = recipes;
